Capston2/Capston2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Capston2.views import HomeView, UserCreateView, UserCreateDoneTV, descriptionView

urlpatterns = [
    path('admin/', admin.site.urls),
    #홈뷰 
    path('', HomeView.as_view(), name='home'), #url 패턴명 = home
    #설명 뷰
    path('description/', descriptionView.as_view(), name='description'),
    # 장고 내장 인증 django.contrib.auth.urls 모듈 가져오기
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    # APP_URLCONF 방식
    # Include 함수 이용, 각각 앱쪽의 url에서 처리
    path('upload/', include('ImgSub.urls')),
    path('photo/', include('photo.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Capston2/ImgSub/urls.py
from django.urls import path
from . import views


app_name = 'ImgSub'
urlpatterns = [
    path('', views.img_upload, name="upload"),

    path('processed/', views.Processed_Img, name="processed_Img"),

    path('processed/conversion/', views.c_upload, name="conversion_upload"),

    path('processed/conversion/final/', views.fin_output, name="final_output"),
]

Capston2/photo/urls.py
from django.urls import path
from photo import views


app_name = 'photo'
urlpatterns = [
    # /photo/
    path('', views.AlbumLV.as_view(), name="index"),

    # /photo/album/ = /photo/
    path('', views.AlbumLV.as_view(), name="album_list"),

    # /photo/album/99
    path('album/<int:pk>/', views.AlbumDV.as_view(), name="album_detail"),

    # /photo/photo/99
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name="photo_detail"),
] 

Capston2/ImgSub/models.py
from django.db import models


class Og_Img(models.Model):
    #원본 이미지 저장
    img = models.ImageField(upload_to='original/')

class Bg_remove(models.Model):
    #배경 제거된 이미지 저장
    rm_img = models.ImageField(upload_to='process/')

class Background(models.Model):
    #배경 이미지
    bg_img = models.ImageField(upload_to='bg/')

class Final_img(models.Model):
    #배경을 합성한 이미지
    fin_img = models.ImageField(upload_to='final/')

Capston2/photo/models.py
from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField # fields.py에서 ThumbnailImageField 클래스 불러오기

class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Discriptions', max_length=100, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,)) # /photo/album/99 형식의 url 반환

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE) # Album 테이블에 연결된 외래키(사진이 소속된 앨범을 가리킴)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('사진 설명', blank=True)
     # 필드를 커스텀필드로도 할 수 있음! // 원본 이미지 및 썸네일 이미지를 둘다 저장하는 필드 // upload_to = 저장할 위치(MEDIA_ROOT 기준), /photo/년도/월 형식으로 저장하겠다.
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('업로드 일자', auto_now_add=True) # 사진이 업로드 되는 시간을 저장

    
    # 내부 클래스 // 객체 리스트 출력 시 순서(title 컬럼 기준으로)
    class Meta: 
        ordering = ('title',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,)) # /photo/photo/99 형식의 url 반환

Capston2/ImgSub/forms.py
from django import forms
from .models import Og_Img, Background

class ImgForm(forms.ModelForm):
    class Meta:
        model = Og_Img
        fields = ['img']
       #S widgets = {'img': forms.HiddenInput()}

    
class BgForm(forms.ModelForm):
    class Meta:
        model = Background
        fields = ('bg_img',)

Capston2/Capston2/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView # 테이블에 새로운 레코드(폼에 입력된 데이터) 생성하는 뷰
from django.contrib.auth.forms import UserCreationForm # User 객체 생성
from django.urls import reverse_lazy # 인자로 URL 패턴을 받음

# 홈페이지 뷰
class HomeView(TemplateView):
    template_name = 'home.html' # 템플릿 뷰를 사용할 시 필수 클래스 변수(template_name), home.html에서 표출하겠다.

class descriptionView(TemplateView):
    template_name = 'description.html'


# 유저 생성 뷰(테이블에 레코드 추가/생성)
class UserCreateView(CreateView):
    template_name = 'registration/register.html' # 가입할 때 사용자에게 보여줄 템플릿
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done') # 폼에 에러 없다면 accounts/register/done/으로 리다이렉트

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html' # 가입 처리 완료 후 사용자에게 보여줄 템플릿

Capston2/ImgSub/views.py
from django.shortcuts import render, redirect
from .models import Og_Img, Bg_remove, Background, Final_img
from .forms import ImgForm, BgForm
from .BackgroundRemove import ImageProcessing, dlab


# 배경제거 이미지 보여주는 페이지
def Processed_Img(request):
    proImg = Og_Img.objects.all()

    return render(request, 'ImgSub/processed_Img.html',{
        'proImg' : proImg,
    })


# 업로드 버튼 누르는 페이지
def img_upload(request):
    if request.method == 'POST':   
        form = ImgForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            absolute_name = request.FILES['img'].name
            img_name = ImageProcessing.segment(dlab, 'ImgSub/../media/original/'+absolute_name, show_orig=False)
            return redirect('processed/')
        else:
            form = ImgForm(None)
    else:
        form = ImgForm()

    return render(request, 'ImgSub/upload.html',{
        'form' : form,
    })
         
#최종 결과물(이미지) 페이지
def fin_output(request):
    proImg2 = Background.objects.all()
    return render(request, 'ImgSub/final_output.html',{
        'proImg2' : proImg2
    })

#배경 이미지 업로드 페이지
def c_upload(request):
    if request.method == 'POST':   
        form2 = BgForm(request.POST, request.FILES)
        if form2.is_valid():
            form2.save()
            file_name = request.FILES['bg_img'].name
            output_path = ImageConversion.segment(dlab, 'ImgSub/../static/test/123.jpg','ImgSub/../media/bg/'+file_name, show_orig=False)
            return redirect('final/')
        else:
            form2 = BgForm(None)
    else:
        form2 = BgForm()
    return render(request, 'ImgSub/img_conversion.html',{
        'form2' : form2,
    })

Capston2/photo/views.py
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo


class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

Capston2/ImgSub/templates/ImgSub/final_output.html
{% extends "base.html" %}
{% load static %}
{% block title %}final_output.html{% endblock %}


{% block content %}
<ul>
    <li>
        <img src="{% static 'final/result2020-11-0913_51_06_902472.png' %}">
    </li>
    <li>
        <a href="{% static 'final/result2020-11-0913_51_06_902472.png' %}" class="btn btn-info" download="">다운로드</a> 
    </li>
</ul>
{% endblock %}

Capston2/ImgSub/templates/ImgSub/img_conversion.html
{% extends "base.html" %}

{% block title %}img_conversion.html{% endblock %}


{% block content %}
<h2>합성할 배경 업로드</h2>
<hr>
<br><br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form2.as_p }}
    <hr>
    <button type="submit" class="btn btn-info">배경합성</button>
</form>
{% endblock %}

Capston2/ImgSub/templates/ImgSub/processed_Img.html
{% extends "base.html" %}
{% load static %}
{% block title %}processed_Img.html{% endblock %}


{% block content %}
    <h2>편집된 이미지</h2>
    <table class="table">
        <thead>
            <tr>
                <th>원본 이미지</th>
                <th>편집 이미지</th>
                <th>다운로드</th>
                <th>배경 합성하기</th>                          
            </tr>
        </thead> 
        <tbody>
            {% for t in proImg %}
                <tr>
                    <td>
                        <img src="{{ t.img.url }}" style="width: 180px;">
                    </td>
            {% endfor %}
                    <td>
                        <img src="{% static 'test/result2020-11-0618_10_57_908271.png' %}" style="width: 180px;">
                    </td>
                    <td>
                        <a href="{% static 'test/result2020-11-0618_10_57_908271.png' %}" class="btn btn-info" download="">다운로드</a> 
                    </td>        
                    <td>
                        <a href="{% url 'blog:conversion_upload' %}" class="btn btn-info">배경합성</a> 
                    </td>
                </tr> 

        </tbody> 
    </table>
{% endblock %}

Capston2/ImgSub/templates/ImgSub/upload.html
{% extends "base.html" %}
{% block title %}img_upload.html{% endblock %}


{% block content %}
<h2>이미지 업로드하기</h2>
<hr>
<br><br>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.img }}
    <hr>
    <button type="submit" class="btn btn-info">사진 업로드</button>
</form>
{% endblock %}

Capston2/photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}


{% block extra-style %}
<style>
    thumbnail {
        border: 5px solid #ccc;
    }
</style>
{% endblock %}
<!-- object는 객체를 지칭하는 용어 -->
{% block content %}

    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span>
        <span class="h5 font-weight-bold">{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">
    

    <div class="row">

{% for photo in object.photo_set.all %}
<div class="col-md-3 mb-5">
    <div class="thumbnail">
        <a href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
        </a>
    </div>
    <ul>
        <li class="font-italic">{{ photo.title }}</li>
        <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
    </ul>
</div>
{% endfor %}

    </div>

{% endblock %}

Capston2/photo/templates/photo/album_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% block extra-style %}
<style>
    thumbnail {
        border: 3px solid #ccc;
    }
</style>
{% endblock %}


{% block content %}
<h2>원하는 배경 샘플 다운 받기</h2>
<hr>
    {% for item in object_list %} <!-- AlbumLV에서 넘겨주는 리스트 객체, 리스트를 순회 -->
    <div class="mt-5">
        <a class="h2" href="{% url 'photo:album_detail' item.id %}"> <!-- photo/album/99의 형태 url에 name인자 참고 -->
            {{ item.name }} <!-- Album객체의 이름 -->
        </a>&emsp;
        <span class="font-italic h5">{{ item.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        {% for photo in item.photo_set.all|slice:":6" %} <!-- 사진 5개씩 한줄에(row) -->
        <div class="ml-5">
            <div class="thumbnail">
                <a href="{{ photo.get_absolute_url }}">
                    <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

{% endblock %}

Capston2/photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}


{% block content %}
<!-- object는 객체를 지칭하는 용어 -->
    <h2 class="mt-5">{{ object.title }}</h2>

    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%;">
            </a>
        </div>

        <ul class="col-md-3 mt-3">
            <li class="h5">사진 설명</li>
                {% if object.description %}<p>{{ object.description|linebreaks }}</p> 
                {% else %}<p>(blank)</p>{% endif %}
            <li class="h5">업로드한 날짜</li>
                <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">앨범 이름</li>
                <p class="font-italic">
                    <a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a>
                </p>
            <li class="h5"><a href="{{ object.image.url }}" class="btn btn-info" download="">다운로드</a></li>
        </ul>
    </div>

{% endblock %}

Capston2/templates/base.html
<!-- base.html은 모든 페이지 공통으로 들어가는 코드임, 상속받는 하위 html에서 수정할 부분을 block으로 표시함(block을 잘 조정해야함)-->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Object Subtractor Project{% endblock %}</title><!-- 기본 타이틀 하위파일에서 오버라이딩 할 수 있음 -->

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
        {% block extra-style %}{% endblock %}<!-- 하위 상속 파일에서 다른 CSS 적용가능 -->
    </head>
    <body style="padding-top:90px;">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-primary fixed-top">
            {% load static %}<!-- 이걸 해야 사진 먹힘 -->
            <span class="navbar-brand mx-5 mb-0"><img src="{% static 'img/VIT_logo.png' %}" width="90px" height="50px"></span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-toggle="collapse" data-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'ImgSub:upload' %}">IMAGE</a> <!-- blog.urls의 name인자 참고 -->
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        <a class="nav-link text-white" href="{% url 'photo:index' %}">SAMPLE</a>
                    </li>
                    <li class="nav-item mx-1 btn btn-primary">
                        {% if user.is_superuser %}
                            <a class="nav-link text-white" href="{% url 'admin:index' %}">Admin</a>
                        {% elif user.is_active %}
                            <a class="nav-link text-white" href="{% url 'photo:index' %}">마이 페이지</a>
                        {% else %}
                            <a class="nav-link text-white" href="{% url 'login' %}">로그인</a>
                        {% endif %}
                    </li>
                </ul>
                <span class="navbar-brand font-weight-bold">Django Object Subtractor</span>
                <ul class="navbar-nav ml-5 mr-5">
                    <li class="nav-item dropdown mx-1 btn btn-primary">
                        {% if user.is_active %}<!-- 사용자가 로그인 되있을 경우 -->
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                            <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a><!-- 로그아웃 클릭시 해당 url로(urls.py에 name인자에 해당하는 url) -->
                            <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a><!-- 비밀번호 변경 클릭시 해당 url로 -->
                        </div>
                        {% else %} <!-- 사용자 비로그인 시 -->
                        <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                            <i class="fas fa-user"></i>&ensp;로그인&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'login' %}">로그인</a> <!-- 로그인 클릭시 해당 url로 -->
                            <a class="dropdown-item" href="{% url 'register' %}">회원가입</a><!-- 회원가입 클릭시 해당 url로 -->
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    
        
        <div class="container">
            {% block content %}{% endblock %} <!-- 하위 페이지마다 본문내용을 다르게 할 수 있음 -->
        </div>
        {% block footer %}{% endblock %}<!-- 하위 페이지 마다 다른 footer 적용 가능 -->

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

        {% block extra-script %}{% endblock %}
    </body>
</html>

Capston2/templates/description.html
{% extends "base.html" %}
{% load static %}
{% block title %}processed_Img.html{% endblock %}


{% block content %} 
<img src="{% static 'img/description.png' %}" style="width: 800px; align-items: center;">
{% endblock %}

Capston2/templates/home.html
<!-- base.html에서 상속 -->
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
  .home-image {
    background-color: black;
    background-image: url("{% static 'img/main.png' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 700px;
  }
  .powered {
    position: relative;
    top: 90%;
    color: #cc0;
    font-weight: bold;
  }
</style>
{% endblock %}


{% block content %}
  <div class="home-image"></div>

  <hr style="margin: 10px 0;">
  <div style="text-align: center;">
    <div>
      <h3 style="text-align: center;">객체 추출 웹사이트</h3>
      <form style="text-align: center;">{% csrf_token %}
        <a href="{% url 'description' %}">
          <input type="button" value="자세히 알아보기">
        </a> 
      </form> 
    </div>
  </div>

{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-dark">
  <div class="text-white font-weight-bold text-right mr-4">Copyright &copy; 2020-2 Capston Design2</div>
</footer>
{% endblock %}